import Head from "next/head";
import { Inter } from "next/font/google";
import { useSession, signOut } from "next-auth/react";
import { useRouter } from "next/router";

import AppWrapper from "@/components/appWrapper";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session, status } = useSession();

  let authenticateText;
  if (status === "authenticated" && session.user) {
    authenticateText = <p>Signed in as {session.user.email}</p>;
  } else {
    authenticateText = <p>Not signed in</p>;
  }

  const router = useRouter();
  const signUserOut = async () => {
    const requestHeaders: HeadersInit = new Headers();
    requestHeaders.set("Content-Type", "application/json");
    const requestOptions = {
      method: "POST",
      headers: requestHeaders,
      body: JSON.stringify({
        token: session?.refreshToken,
      }),
    };
    const logoutEndpoint = await fetch(
      `${process.env.API_URL}/api/auth/logout`,
      requestOptions
    );
    if (logoutEndpoint.ok) {
      signOut({ redirect: false }).then(({ ok, error }: any) => {
        if (ok) {
          router.push("/login");
        } else {
          console.log(error);
        }
      });
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppWrapper>
        <h1>Du er logget ind!</h1>
        {authenticateText}
        <button onClick={signUserOut}>Log ud</button>
      </AppWrapper>
    </>
  );
}
